### ISSUE TITLE
Add a "plan" or a "dry run" option to all commands

### ISSUE THREAD

**Issue by sverch** [getcloudless/cloudless#32]
One consistent bit of feedback I've gotten is that people want to know what the tool is actually going to do before they run it on their infrastructure.

This would mean some refactoring to explicitly have a "discovery" phase and an "execution" phase, which would probably be good anyway.  It also raises the question of what to do if something changes between discovery and execution.  So far the strategy has been to make everything idempotent, which would probably be the right thing to continue.

Something like:

```
cldls --dry-run service create example-network example-apache examples/apache
Doing dry run...
network:
  name: example-network
  services:
    - added: true
      name: example-apache
```

This could also support a "--dry-run-provider" option to show what would be created in terms of the provider specific names/ids.
